name: Auto Merge to QA

on:
  workflow_dispatch:

jobs:
  auto_merge_to_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "shahzaib.kkhowaja@github.com"
          git config --global user.name "shahzaib-khowaja"

      - name: Create Pull Request to QA
        run: |
 
          # Create a pull request to QA
          gh pr create --base branch1 --head branch2 --title "Auto Merge to QA" --body "Automatically created pull request from development to QA."
